name: "install uv"
description: "installs uv using the community action"
runs:
  using: composite
  steps:
    - name: install uv
      uses: "astral-sh/setup-uv@v6"
    - name: install Python dependencies
      run: uv sync --extra dev
      shell: bash